/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./App.tsx", "./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        black: ["Poppins-Black"],
        blackItalic: ["Poppins-BlackItalic"],
        bold: ["Poppins-Bold"],
        boldItalic: ["Poppins-BoldItalic"],
        extraBold: ["Poppins-ExtraBold"],
        extraBoldItalic: ["Poppins-ExtraBoldItalic"],
        extraLight: ["Poppins-ExtraLight"],
        extraLightItalic: ["Poppins-ExtraLightItalic"],
        italic: ["Poppins-Italic"],
        light: ["Poppins-Light"],
        lightItalic: ["Poppins-LightItalic"],
        medium: ["Poppins-Medium"],
        mediumItalic: ["Poppins-MediumItalic"],
        regular: ["Poppins-Regular"],
        semibold: ["Poppins-Semibold"],
        semiboldItalic: ["Poppins-SemiboldItalic"],
        thin: ["Poppins-Thin"],
        thinItalic: ["Poppins-ThinItalic"],
      },
      colors: {
        "turquoise-1": "#081313",
        "turquoise-2": "#0D1B1B",
        "turquoise-3": "#012D2D",
        "turquoise-4": "#003B3C",
        "turquoise-5": "#004849",
        "turquoise-6": "#005758",
        "turquoise-7": "#006A6B",
        "turquoise-8": "#008384",
        "turquoise-9": "#30CFD0",
        "turquoise-10": "#18C4C5",
        "turquoise-11": "#36D3D4",
        "turquoise-12": "#B6F1F1",
        "gris-1": "#111113",
        "gris-2": "#19191B",
        "gris-3": "#222325",
        "gris-4": "#292A2E",
        "gris-5": "#303136",
        "gris-6": "#393A40",
        "gris-7": "#46484F",
        "gris-8": "#5F606A",
        "gris-9": "#6C6E79",
        "gris-10": "#797B86",
        "gris-11": "#B2B3BD",
        "gris-12": "#EEEEF0",
        "vert": "#00E074",
        "jaune": "#FFDC10",
        "rouge": "#FF1474",
      }
    },
  },
  plugins: [],
}